FROM python:3.12-slim
WORKDIR /app
COPY api-tractian/api /app/api
COPY api-tractian/data /app/data
RUN pip install --no-cache-dir /app/api
WORKDIR /app/api
EXPOSE 8000
CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

